apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
    - name: my-container
      image: 637423594714.dkr.ecr.<your-region>.amazonaws.com/sqs-to-s3:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 80
